apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: us-central1-docker.pkg.dev/mlops-deployment-kube/docker-repo/mlops-app:v1
        env:
        - name: LC_ALL
          value: C.UTF-8
        - name: LANG
          value: C.UTF-8
        - name: FLASK_APP
          value: api/app.py
        ports:
        - containerPort: 80